#include "ThemidaSDK/ThemidaSDK.h"

#define VM_TIGER_WHITE_START
#define VM_TIGER_WHITE_END

#define VM_TIGER_RED_START
#define VM_TIGER_RED_END

#define VM_TIGER_BLACK_START
#define VM_TIGER_BLACK_END

#define VM_FISH_WHITE_START
#define VM_FISH_WHITE_END

#define VM_FISH_RED_START
#define VM_FISH_RED_END

#define VM_FISH_BLACK_START
#define VM_FISH_BLACK_END

#define VM_PUMA_WHITE_START
#define VM_PUMA_WHITE_END

#define VM_PUMA_RED_START
#define VM_PUMA_RED_END

#define VM_PUMA_BLACK_START
#define VM_PUMA_BLACK_END

#define VM_SHARK_WHITE_START
#define VM_SHARK_WHITE_END

#define VM_SHARK_RED_START
#define VM_SHARK_RED_END 

#define VM_SHARK_BLACK_START
#define VM_SHARK_BLACK_END

#define VM_DOLPHIN_WHITE_START
#define VM_DOLPHIN_WHITE_END

#define VM_DOLPHIN_RED_START
#define VM_DOLPHIN_RED_END

#define VM_DOLPHIN_BLACK_START
#define VM_DOLPHIN_BLACK_END

#define VM_EAGLE_WHITE_START
#define VM_EAGLE_WHITE_END

#define VM_EAGLE_RED_START
#define VM_EAGLE_RED_END

#define VM_EAGLE_BLACK_START
#define VM_EAGLE_BLACK_END

#define VM_MUTATE_ONLY_START
#define VM_MUTATE_ONLY_END